// Generated by scripts/generate-basic-registry.mjs.
export const KUMO_COMPONENT_PROP_SCHEMAS = {
  Autocomplete: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    container: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    sideOffset: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    autocomplete: {
      type: 'HTMLInputAttributes["autocomplete"]',
      runtime: {
        kind: "string",
      },
    },
    clearOnDeselect: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    defaultValue: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onblur: {
      type: "(event: FocusEvent & { currentTarget: HTMLInputElement }) => void",
      runtime: {
        kind: "function",
      },
    },
    onfocus: {
      type: "(event: FocusEvent & { currentTarget: HTMLInputElement }) => void",
      runtime: {
        kind: "function",
      },
    },
    oninput: {
      type: "(event: Event & { currentTarget: HTMLInputElement }) => void",
      runtime: {
        kind: "function",
      },
    },
    onkeydown: {
      type: "(event: KeyboardEvent & { currentTarget: HTMLInputElement }) => void",
      runtime: {
        kind: "function",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    placeholder: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    size: {
      type: "KumoAutocompleteSize",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    allowDeselect: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
            props: {
              message: {
                kind: "union",
                options: [
                  {
                    kind: "snippet",
                  },
                  {
                    kind: "string",
                  },
                ],
                required: true,
              },
            },
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  Badge: {
    appearance: {
      type: "KumoBadgeAppearance",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoBadgeVariant",
      runtime: {
        kind: "string",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
  },
  Banner: {
    action: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    icon: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    text: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    title: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoBannerVariant",
      values: ["default", "alert", "error"],
      runtime: {
        kind: "string",
      },
    },
  },
  Breadcrumbs: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    copiedLabel: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onCopy: {
      type: "() => void",
      runtime: {
        kind: "function",
      },
    },
    text: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    icon: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    loading: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    mobileChildren: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    size: {
      type: "KumoBreadcrumbsSize",
      values: ["sm", "base"],
      runtime: {
        kind: "string",
      },
    },
  },
  Button: {
    shape: {
      type: "KumoButtonShape",
      values: ["base", "square", "circle"],
    },
    size: {
      type: "KumoButtonSize",
      values: ["xs", "sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoButtonVariant",
      values: ["primary", "secondary", "ghost", "destructive", "secondary-destructive", "outline"],
      runtime: {
        kind: "string",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    icon: {
      type: "Component",
    },
    loading: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    title: {
      type: "Snippet | string | null",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    external: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  Checkbox: {
    legend: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    error: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    defaultValue: {
      type: "string[]",
      runtime: {
        kind: "array",
        item: {
          kind: "string",
        },
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onValueChange: {
      type: "(value: string[]) => void",
      runtime: {
        kind: "function",
      },
    },
    allValues: {
      type: "string[]",
      runtime: {
        kind: "array",
        item: {
          kind: "string",
        },
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    controlFirst: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoCheckboxVariant",
      values: ["default", "error"],
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    checked: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    indeterminate: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onCheckedChange: {
      type: "(checked: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    "aria-labelledby": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
  },
  ClipboardText: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    labels: {
      type: "ClipboardTextLabels",
      runtime: {
        kind: "object",
        props: {
          copyAction: {
            kind: "string",
            required: false,
          },
        },
      },
    },
    onCopy: {
      type: "() => void",
      runtime: {
        kind: "function",
      },
    },
    size: {
      type: "KumoClipboardTextSize",
      values: ["sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    text: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    textToCopy: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    tooltip: {
      type: "ClipboardTextTooltipConfig",
      runtime: {
        kind: "object",
        props: {
          text: {
            kind: "string",
            required: false,
          },
          copiedText: {
            kind: "string",
            required: false,
          },
          side: {
            kind: "union",
            options: [
              {
                kind: "literal",
                value: "top",
              },
              {
                kind: "literal",
                value: "bottom",
              },
              {
                kind: "literal",
                value: "left",
              },
              {
                kind: "literal",
                value: "right",
              },
            ],
            required: false,
          },
        },
      },
    },
  },
  CloudflareLogo: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    color: {
      type: "CloudflareLogoColor",
      values: ["color", "black", "white"],
    },
    variant: {
      type: "CloudflareLogoVariant",
      values: ["glyph", "full"],
    },
  },
  Collapsible: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    forceMount: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    hiddenUntilFound: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
  },
  Combobox: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    removeLabel: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    value: {
      type: "string | string[]",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "array",
            item: {
              kind: "string",
            },
          },
        ],
      },
    },
    container: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    sideOffset: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    autocomplete: {
      type: 'HTMLInputAttributes["autocomplete"]',
      runtime: {
        kind: "string",
      },
    },
    clearOnDeselect: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    defaultValue: {
      type: "string | string[]",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "array",
            item: {
              kind: "string",
            },
          },
        ],
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onblur: {
      type: "(event: FocusEvent & { currentTarget: HTMLInputElement }) => void",
      runtime: {
        kind: "function",
      },
    },
    oninput: {
      type: "(event: Event & { currentTarget: HTMLInputElement }) => void",
      runtime: {
        kind: "function",
      },
    },
    onValueChange: {
      type: "(value: string | string[]) => void",
      runtime: {
        kind: "function",
      },
    },
    placeholder: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    size: {
      type: "KumoComboboxSize",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    clearLabel: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    showOptionsLabel: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    inputSide: {
      type: "KumoComboboxInputSide",
      values: ["right", "top"],
      runtime: {
        kind: "string",
      },
    },
    renderItem: {
      type: "Snippet<[value: string]>",
      runtime: {
        kind: "snippet",
      },
    },
    child: {
      type: "Snippet<[{ props: Record<string, unknown> }]>",
      runtime: {
        kind: "snippet",
      },
    },
    allowDeselect: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
            props: {
              message: {
                kind: "union",
                options: [
                  {
                    kind: "snippet",
                  },
                  {
                    kind: "string",
                  },
                ],
                required: true,
              },
            },
          },
        ],
      },
    },
    items: {
      type: "ComboboxItemDescriptor[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            disabled: {
              kind: "boolean",
              required: false,
            },
            label: {
              kind: "string",
              required: true,
            },
            value: {
              kind: "string",
              required: true,
            },
          },
        },
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    multiple: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  CommandPalette: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    forceMount: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    keywords: {
      type: "string[]",
      runtime: {
        kind: "array",
        item: {
          kind: "string",
        },
      },
    },
    onSelect: {
      type: "() => void",
      runtime: {
        kind: "function",
      },
    },
    progress: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    breadcrumbHighlights: {
      type: "HighlightRange[][]",
      runtime: {
        kind: "array",
        item: {
          kind: "array",
          item: {
            kind: "array",
            items: [
              {
                kind: "number",
              },
              {
                kind: "number",
              },
            ],
          },
        },
      },
    },
    breadcrumbs: {
      type: "string[]",
      runtime: {
        kind: "array",
        item: {
          kind: "string",
        },
      },
    },
    description: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    external: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    icon: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    nonInteractive: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    showArrow: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    title: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    titleHighlights: {
      type: "HighlightRange[]",
      runtime: {
        kind: "array",
        item: {
          kind: "array",
          items: [
            {
              kind: "number",
            },
            {
              kind: "number",
            },
          ],
        },
      },
    },
    filter: {
      type: "(value: string, search: string, keywords?: string[]) => number",
      runtime: {
        kind: "function",
      },
    },
    label: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    loop: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    shouldFilter: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    highlights: {
      type: "HighlightRange[]",
      runtime: {
        kind: "array",
        item: {
          kind: "array",
          items: [
            {
              kind: "number",
            },
            {
              kind: "number",
            },
          ],
        },
      },
    },
    text: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
  },
  Code: {
    code: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    lang: {
      type: "KumoCodeLang",
      values: ["ts", "tsx", "jsonc", "bash", "css"],
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    values: {
      type: "Record<string, { highlight?: boolean; value: string }>",
      runtime: {
        kind: "record",
        item: {
          kind: "object",
          props: {
            highlight: {
              kind: "boolean",
              required: false,
            },
            value: {
              kind: "string",
              required: true,
            },
          },
        },
      },
    },
  },
  Chart: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    color: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    inactive: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    unit: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    defaultNodeColor: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    echarts: {
      type: "typeof echarts",
      runtime: {
        kind: "object",
      },
    },
    formatValue: {
      type: "(value: number) => string",
      runtime: {
        kind: "function",
      },
    },
    height: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    isDarkMode: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    left: {
      type: "number | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "number",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    linkColor: {
      type: '"gradient" | "gray"',
      values: ["gradient", "gray"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "gradient",
          },
          {
            kind: "literal",
            value: "gray",
          },
        ],
      },
    },
    linkOpacity: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    links: {
      type: "SankeyLinkData[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            id: {
              kind: "string",
              required: false,
            },
            isDrillable: {
              kind: "boolean",
              required: false,
            },
            source: {
              kind: "number",
              required: true,
            },
            target: {
              kind: "number",
              required: true,
            },
            value: {
              kind: "number",
              required: true,
            },
          },
        },
      },
    },
    nodePadding: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    nodeWidth: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    nodes: {
      type: "SankeyNodeData[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            childCount: {
              kind: "number",
              required: false,
            },
            color: {
              kind: "string",
              required: false,
            },
            id: {
              kind: "string",
              required: false,
            },
            isDrillable: {
              kind: "boolean",
              required: false,
            },
            name: {
              kind: "string",
              required: true,
            },
            tooltipData: {
              kind: "record",
              item: {
                kind: "union",
                options: [
                  {
                    kind: "number",
                  },
                  {
                    kind: "string",
                  },
                ],
              },
              required: false,
            },
            value: {
              kind: "number",
              required: false,
            },
          },
        },
      },
    },
    onLinkClick: {
      type: "(link: SankeyLinkData) => void",
      runtime: {
        kind: "function",
      },
    },
    onNodeClick: {
      type: "(node: SankeyNodeData) => void",
      runtime: {
        kind: "function",
      },
    },
    right: {
      type: "number | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "number",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    showNodeValues: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    showTooltip: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    tooltipFormatter: {
      type: "(params: SankeyTooltipParams) => string",
      runtime: {
        kind: "function",
      },
    },
    ariaDescription: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    data: {
      type: "TimeseriesData[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            color: {
              kind: "string",
              required: true,
            },
            data: {
              kind: "array",
              item: {
                kind: "array",
                items: [
                  {
                    kind: "number",
                  },
                  {
                    kind: "number",
                  },
                ],
              },
              required: true,
            },
            name: {
              kind: "string",
              required: true,
            },
          },
        },
      },
    },
    gradient: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    incomplete: {
      type: "{ after?: number; before?: number }",
      runtime: {
        kind: "object",
        props: {
          after: {
            kind: "number",
            required: false,
          },
          before: {
            kind: "number",
            required: false,
          },
        },
      },
    },
    loading: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onTimeRangeChange: {
      type: "(from: number, to: number) => void",
      runtime: {
        kind: "function",
      },
    },
    optionUpdateBehavior: {
      type: "SetOptionOpts",
      runtime: {
        kind: "object",
      },
    },
    tooltipValueFormat: {
      type: "(value: number) => string",
      runtime: {
        kind: "function",
      },
    },
    type: {
      type: '"bar" | "line"',
      values: ["bar", "line"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "bar",
          },
          {
            kind: "literal",
            value: "line",
          },
        ],
      },
    },
    xAxisName: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    xAxisTickCount: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    xAxisTickFormat: {
      type: "(value: number) => string",
      runtime: {
        kind: "function",
      },
    },
    yAxisName: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    yAxisTickCount: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    yAxisTickFormat: {
      type: "(value: number) => string",
      runtime: {
        kind: "function",
      },
    },
    yAxisTickLabelFormat: {
      type: "(value: number) => string",
      runtime: {
        kind: "function",
      },
    },
    onEvents: {
      type: "Partial<ChartEvents>",
      runtime: {
        kind: "object",
      },
    },
    options: {
      type: "KumoChartOption",
      runtime: {
        kind: "object",
      },
    },
    ref: {
      type: "echarts.ECharts | null",
      runtime: {
        kind: "object",
      },
    },
  },
  DatePicker: {
    mode: {
      type: "DatePickerMode",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "single",
          },
          {
            kind: "literal",
            value: "multiple",
          },
          {
            kind: "literal",
            value: "range",
          },
        ],
      },
    },
    months: {
      type: "Month<DateValue>[]",
      runtime: {
        kind: "array",
      },
    },
    weekdays: {
      type: "string[]",
      runtime: {
        kind: "array",
        item: {
          kind: "string",
        },
      },
    },
    calendarLabel: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet<[DatePickerSnippetProps]>",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disableDaysOutsideMonth: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    excludeDisabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    fixedWeeks: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    footer: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    initialFocus: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    isDateDisabled: {
      type: "DateMatcher",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "boolean",
          },
          {
            kind: "function",
          },
          {
            kind: "array",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    isDateUnavailable: {
      type: "DateMatcher",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "boolean",
          },
          {
            kind: "function",
          },
          {
            kind: "array",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    locale: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    maxDays: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    maxValue: {
      type: "DateValue",
      runtime: {
        kind: "object",
      },
    },
    minDays: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    minValue: {
      type: "DateValue",
      runtime: {
        kind: "object",
      },
    },
    monthFormat: {
      type: 'Intl.DateTimeFormatOptions["month"] | ((month: number) => string)',
      runtime: {
        kind: "function",
      },
    },
    numberOfMonths: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    onEndValueChange: {
      type: "(value: DateValue | undefined) => void",
      runtime: {
        kind: "function",
      },
    },
    onPlaceholderChange: {
      type: "(value: DateValue) => void",
      runtime: {
        kind: "function",
      },
    },
    onStartValueChange: {
      type: "(value: DateValue | undefined) => void",
      runtime: {
        kind: "function",
      },
    },
    onValueChange: {
      type: "(value: DatePickerValue) => void",
      runtime: {
        kind: "function",
      },
    },
    pagedNavigation: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    placeholder: {
      type: "DateValue",
      runtime: {
        kind: "object",
      },
    },
    preventDeselect: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    readonly: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    ref: {
      type: "HTMLDivElement | null",
      runtime: {
        kind: "object",
      },
    },
    value: {
      type: "DatePickerValue",
      runtime: {
        kind: "array",
      },
    },
    weekStartsOn: {
      type: "WeekStartsOn",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: 0,
          },
          {
            kind: "literal",
            value: 1,
          },
          {
            kind: "literal",
            value: 2,
          },
          {
            kind: "literal",
            value: 3,
          },
          {
            kind: "literal",
            value: 4,
          },
          {
            kind: "literal",
            value: 5,
          },
          {
            kind: "literal",
            value: 6,
          },
        ],
      },
    },
    weekdayFormat: {
      type: 'Intl.DateTimeFormatOptions["weekday"]',
      runtime: {
        kind: "string",
      },
    },
    yearFormat: {
      type: 'Intl.DateTimeFormatOptions["year"] | ((year: number) => string)',
      runtime: {
        kind: "function",
      },
    },
  },
  DateRangePicker: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onEndDateChange: {
      type: "(date: Date | null) => void",
      runtime: {
        kind: "function",
      },
    },
    onStartDateChange: {
      type: "(date: Date | null) => void",
      runtime: {
        kind: "function",
      },
    },
    onValueChange: {
      type: "(value: DateRange) => void",
      runtime: {
        kind: "function",
      },
    },
    size: {
      type: "KumoDateRangePickerSize",
      values: ["sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    timezone: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    value: {
      type: "DateRange",
      runtime: {
        kind: "object",
      },
    },
    variant: {
      type: "KumoDateRangePickerVariant",
      values: ["default", "subtle"],
      runtime: {
        kind: "string",
      },
    },
  },
  Dialog: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    container: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    size: {
      type: "KumoDialogSize",
      values: ["base", "sm", "lg", "xl"],
      runtime: {
        kind: "string",
      },
    },
    style: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    to: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    role: {
      type: "KumoDialogRole",
      values: ["dialog", "alertdialog"],
      runtime: {
        kind: "string",
      },
    },
    disablePointerDismissal: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    level: {
      type: "1 | 2 | 3 | 4 | 5 | 6",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: 1,
          },
          {
            kind: "literal",
            value: 2,
          },
          {
            kind: "literal",
            value: 3,
          },
          {
            kind: "literal",
            value: 4,
          },
          {
            kind: "literal",
            value: 5,
          },
          {
            kind: "literal",
            value: 6,
          },
        ],
      },
    },
  },
  Dropdown: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    to: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    dir: {
      type: '"ltr" | "rtl"',
      values: ["ltr", "rtl"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "ltr",
          },
          {
            kind: "literal",
            value: "rtl",
          },
        ],
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    variant: {
      type: "KumoDropdownVariant",
      values: ["default", "danger"],
      runtime: {
        kind: "string",
      },
    },
  },
  Empty: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    commandLine: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    contents: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    description: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    icon: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    size: {
      type: "KumoEmptySize",
      values: ["sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    title: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
  },
  Field: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "NormalizedFieldError",
      runtime: {
        kind: "object",
      },
    },
    for: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    hideLabel: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    controlFirst: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  Flow: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    connectors: {
      type: "FlowConnector[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            disabled: {
              kind: "boolean",
              required: false,
            },
            fromId: {
              kind: "string",
              required: false,
            },
            isBottom: {
              kind: "boolean",
              required: false,
            },
            single: {
              kind: "boolean",
              required: false,
            },
            toId: {
              kind: "string",
              required: false,
            },
            x1: {
              kind: "number",
              required: true,
            },
            x2: {
              kind: "number",
              required: true,
            },
            y1: {
              kind: "number",
              required: true,
            },
            y2: {
              kind: "number",
              required: true,
            },
          },
        },
      },
    },
    markerId: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    type: {
      type: "FlowAnchorType",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "start",
          },
          {
            kind: "literal",
            value: "end",
          },
        ],
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    align: {
      type: "FlowAlign",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "start",
          },
          {
            kind: "literal",
            value: "center",
          },
        ],
      },
    },
    canvas: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onOverflowChange: {
      type: "(overflow: { x: boolean; y: boolean }) => void",
      runtime: {
        kind: "function",
      },
    },
    orientation: {
      type: "FlowOrientation",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "horizontal",
          },
          {
            kind: "literal",
            value: "vertical",
          },
        ],
      },
    },
    padding: {
      type: "{ x?: number; y?: number }",
      runtime: {
        kind: "object",
        props: {
          x: {
            kind: "number",
            required: false,
          },
          y: {
            kind: "number",
            required: false,
          },
        },
      },
    },
  },
  Grid: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    gap: {
      type: "KumoGridGap",
      values: ["none", "sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    mobileDivider: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    variant: {
      type: "KumoGridVariant",
      values: ["2up", "side-by-side", "2-1", "1-2", "1-3up", "3up", "4up", "6up", "1-2-4up"],
      runtime: {
        kind: "string",
      },
    },
  },
  Input: {
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
            props: {
              message: {
                kind: "union",
                options: [
                  {
                    kind: "snippet",
                  },
                  {
                    kind: "string",
                  },
                ],
                required: true,
              },
            },
          },
        ],
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    size: {
      type: "KumoInputSize",
      values: ["xs", "sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    value: {
      type: "string | number | string[] | undefined",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "number",
          },
          {
            kind: "array",
            item: {
              kind: "string",
            },
          },
        ],
      },
    },
    variant: {
      type: "KumoInputVariant",
      values: ["default", "error"],
      runtime: {
        kind: "string",
      },
    },
    passwordManagerIgnore: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    focusIndicator: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    parentFocusIndicator: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  InputGroup: {
    align: {
      type: '"start" | "end"',
      values: ["start", "end"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "start",
          },
          {
            kind: "literal",
            value: "end",
          },
        ],
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    containsButton: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    tooltip: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    tooltipSide: {
      type: "KumoTooltipSide",
      runtime: {
        kind: "string",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    value: {
      type: "string | number | string[] | undefined",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "number",
          },
          {
            kind: "array",
            item: {
              kind: "string",
            },
          },
        ],
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
            props: {
              message: {
                kind: "union",
                options: [
                  {
                    kind: "snippet",
                  },
                  {
                    kind: "string",
                  },
                ],
                required: true,
              },
            },
          },
        ],
      },
    },
    focusMode: {
      type: "InputGroupFocusMode",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "container",
          },
          {
            kind: "literal",
            value: "individual",
          },
        ],
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    size: {
      type: "KumoInputSize",
      values: ["xs", "sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
  },
  Label: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    showOptional: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    tooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    for: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    asContent: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  LayerCard: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    as: {
      type: "keyof HTMLElementTagNameMap",
      runtime: {
        kind: "string",
      },
    },
    layered: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  Switch: {
    checked: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onCheckedChange: {
      type: "(checked: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    size: {
      type: "KumoSwitchSize",
      values: ["sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    transitioning: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoSwitchVariant",
      values: ["default", "neutral"],
      runtime: {
        kind: "string",
      },
    },
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    "aria-labelledby": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    controlFirst: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    legend: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
  },
  TableOfContents: {
    active: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    href: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    child: {
      type: "Snippet<[{ props: Record<string, unknown> & { class: string } }]>",
      runtime: {
        kind: "snippet",
      },
    },
    onclick: {
      type: "(event: MouseEvent) => void",
      runtime: {
        kind: "function",
      },
    },
  },
  Tabs: {
    activateOnFocus: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    indicatorClassName: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    listClassName: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    selectedValue: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    size: {
      type: "KumoTabsSize",
      values: ["base", "sm"],
      runtime: {
        kind: "string",
      },
    },
    tabs: {
      type: "TabsItem[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            class: {
              kind: "string",
              required: false,
            },
            disabled: {
              kind: "boolean",
              required: false,
            },
            label: {
              kind: "union",
              options: [
                {
                  kind: "snippet",
                },
                {
                  kind: "string",
                },
              ],
              required: true,
            },
            value: {
              kind: "string",
              required: true,
            },
          },
        },
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoTabsVariant",
      values: ["segmented", "underline"],
      runtime: {
        kind: "string",
      },
    },
  },
  Link: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoLinkVariant",
      values: ["inline", "current", "plain"],
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    to: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
  },
  Loader: {
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    size: {
      type: "KumoLoaderSize | number",
      values: ["sm", "base", "lg"],
      runtime: {
        kind: "number",
      },
    },
    blockHeight: {
      type: "string | number",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "number",
          },
        ],
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    maxDelay: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    maxDuration: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    maxWidth: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    minDelay: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    minDuration: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    minWidth: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
  },
  Menubar: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    isActive: {
      type: "number | boolean | string | undefined",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "number",
          },
          {
            kind: "boolean",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    optionIds: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    options: {
      type: "MenuBarOption[]",
      runtime: {
        kind: "array",
        item: {
          kind: "object",
          props: {
            icon: {
              kind: "snippet",
              required: true,
            },
            id: {
              kind: "union",
              options: [
                {
                  kind: "number",
                },
                {
                  kind: "string",
                },
              ],
              required: false,
            },
            onSelect: {
              kind: "function",
              required: true,
            },
            tooltip: {
              kind: "string",
              required: true,
            },
          },
        },
      },
    },
  },
  Meter: {
    value: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    min: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    max: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    customValue: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    showValue: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    trackClass: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    indicatorClass: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
  },
  Pagination: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    controls: {
      type: "KumoPaginationControls",
      values: ["full", "simple"],
    },
    pageSelector: {
      type: '"input" | "dropdown"',
      values: ["input", "dropdown"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "input",
          },
          {
            kind: "literal",
            value: "dropdown",
          },
        ],
      },
    },
    text: {
      type: "Snippet<[props: PaginationInfoSnippetProps]>",
      runtime: {
        kind: "snippet",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    onValueChange: {
      type: "(size: number) => void",
      runtime: {
        kind: "function",
      },
    },
    options: {
      type: "number[]",
      runtime: {
        kind: "array",
        item: {
          kind: "number",
        },
      },
    },
    value: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    page: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    pageShowingRange: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    perPage: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    totalCount: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    labels: {
      type: "PaginationLabels",
      runtime: {
        kind: "object",
        props: {
          navigation: {
            kind: "string",
            required: false,
          },
          firstPage: {
            kind: "string",
            required: false,
          },
          previousPage: {
            kind: "string",
            required: false,
          },
          nextPage: {
            kind: "string",
            required: false,
          },
          lastPage: {
            kind: "string",
            required: false,
          },
          pageNumber: {
            kind: "string",
            required: false,
          },
          pageSize: {
            kind: "string",
            required: false,
          },
        },
      },
    },
    setPage: {
      type: "(page: number) => void",
      runtime: {
        kind: "function",
      },
    },
  },
  Popover: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    to: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    side: {
      type: "KumoPopoverSide",
      values: ["top", "bottom", "left", "right"],
      runtime: {
        kind: "string",
      },
    },
  },
  Radio: {
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    "aria-labelledby": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    appearance: {
      type: "KumoRadioAppearance",
      values: ["default", "card"],
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    controlPosition: {
      type: "RadioControlPosition",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "start",
          },
          {
            kind: "literal",
            value: "end",
          },
        ],
      },
    },
    defaultValue: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    error: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    legend: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    orientation: {
      type: '"vertical" | "horizontal"',
      values: ["vertical", "horizontal"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "vertical",
          },
          {
            kind: "literal",
            value: "horizontal",
          },
        ],
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    variant: {
      type: "KumoRadioVariant",
      values: ["default", "error"],
      runtime: {
        kind: "string",
      },
    },
  },
  Select: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    value: {
      type: "string | string[]",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "array",
            item: {
              kind: "string",
            },
          },
        ],
      },
    },
    "aria-label": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    "aria-labelledby": {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    allowDeselect: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    container: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    defaultValue: {
      type: "string | string[]",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "array",
            item: {
              kind: "string",
            },
          },
        ],
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
            props: {
              message: {
                kind: "union",
                options: [
                  {
                    kind: "snippet",
                  },
                  {
                    kind: "string",
                  },
                ],
                required: true,
              },
            },
          },
        ],
      },
    },
    hideLabel: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    items: {
      type: "SelectItems",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "record",
            item: {
              kind: "union",
              options: [
                {
                  kind: "string",
                },
                {
                  kind: "object",
                  props: {
                    disabled: {
                      kind: "boolean",
                      required: false,
                    },
                    label: {
                      kind: "string",
                      required: true,
                    },
                  },
                },
              ],
            },
          },
          {
            kind: "array",
            item: {
              kind: "object",
              props: {
                disabled: {
                  kind: "boolean",
                  required: false,
                },
                label: {
                  kind: "string",
                  required: true,
                },
                value: {
                  kind: "string",
                  required: true,
                },
              },
            },
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    loading: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    multiple: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    name: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onValueChange: {
      type: "(value: string | string[]) => void",
      runtime: {
        kind: "function",
      },
    },
    placeholder: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    required: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    size: {
      type: "KumoSelectSize",
      runtime: {
        kind: "string",
      },
    },
  },
  SensitiveInput: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    defaultValue: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    description: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
            props: {
              message: {
                kind: "union",
                options: [
                  {
                    kind: "snippet",
                  },
                  {
                    kind: "string",
                  },
                ],
                required: true,
              },
            },
          },
        ],
      },
    },
    label: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    labelTooltip: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    onCopy: {
      type: "() => void",
      runtime: {
        kind: "function",
      },
    },
    onValueChange: {
      type: "(value: string) => void",
      runtime: {
        kind: "function",
      },
    },
    readonly: {
      type: "boolean | null",
      runtime: {
        kind: "boolean",
      },
    },
    size: {
      type: "KumoSensitiveInputSize",
      runtime: {
        kind: "string",
      },
    },
    value: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "KumoSensitiveInputVariant",
      runtime: {
        kind: "string",
      },
    },
  },
  Sidebar: {
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    id: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    collapsible: {
      type: "SidebarCollapsible",
      values: ["icon", "offcanvas", "none"],
    },
    defaultOpen: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    placeholder: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    shortcut: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    active: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    href: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    icon: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    linkProps: {
      type: 'Omit<HTMLAnchorAttributes, "children" | "class" | "href">',
      runtime: {
        kind: "object",
      },
    },
    size: {
      type: "SidebarMenuButtonSize",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "base",
          },
          {
            kind: "literal",
            value: "sm",
          },
        ],
      },
    },
    tooltip: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    defaultWidth: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    maxWidth: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    minWidth: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    onWidthChange: {
      type: "(width: number) => void",
      runtime: {
        kind: "function",
      },
    },
    resizable: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    side: {
      type: "SidebarSide",
      values: ["left", "right"],
    },
    style: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    variant: {
      type: "SidebarVariant",
      values: ["sidebar", "floating", "inset"],
    },
    width: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    section: {
      type: '"content" | "footer" | "header"',
      values: ["content", "footer", "header"],
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "content",
          },
          {
            kind: "literal",
            value: "footer",
          },
          {
            kind: "literal",
            value: "header",
          },
        ],
      },
    },
    ref: {
      type: "HTMLElement | null",
      runtime: {
        kind: "object",
      },
    },
  },
  Surface: {
    as: {
      type: "keyof HTMLElementTagNameMap",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    color: {
      type: "KumoSurfaceColor",
      values: ["primary", "secondary"],
      runtime: {
        kind: "string",
      },
    },
  },
  Table: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    sticky: {
      type: "boolean",
      values: ["left", "right"],
      runtime: {
        kind: "boolean",
      },
    },
    checked: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    indeterminate: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    label: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    onCheckedChange: {
      type: "(checked: boolean, eventDetails?: CheckboxChangeEventDetails) => void",
      runtime: {
        kind: "function",
      },
    },
    onValueChange: {
      type: "(checked: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    variant: {
      type: "KumoTableRowVariant",
      values: ["default", "selected"],
      runtime: {
        kind: "string",
      },
    },
    layout: {
      type: "KumoTableLayout",
      values: ["auto", "fixed"],
      runtime: {
        kind: "string",
      },
    },
  },
  Text: {
    variant: {
      type: "KumoTextVariant",
      values: [
        "heading1",
        "heading2",
        "heading3",
        "body",
        "secondary",
        "success",
        "error",
        "mono",
        "mono-secondary",
      ],
      runtime: {
        kind: "string",
      },
    },
    size: {
      type: "KumoTextSize",
      values: ["xs", "sm", "base", "lg"],
      runtime: {
        kind: "string",
      },
    },
    bold: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    truncate: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    as: {
      type: "TextElement",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "h1",
          },
          {
            kind: "literal",
            value: "h2",
          },
          {
            kind: "literal",
            value: "h3",
          },
          {
            kind: "literal",
            value: "h4",
          },
          {
            kind: "literal",
            value: "h5",
          },
          {
            kind: "literal",
            value: "h6",
          },
          {
            kind: "literal",
            value: "p",
          },
          {
            kind: "literal",
            value: "span",
          },
          {
            kind: "literal",
            value: "label",
          },
          {
            kind: "literal",
            value: "dt",
          },
          {
            kind: "literal",
            value: "dd",
          },
          {
            kind: "literal",
            value: "li",
          },
          {
            kind: "literal",
            value: "figcaption",
          },
          {
            kind: "literal",
            value: "legend",
          },
          {
            kind: "literal",
            value: "pre",
          },
          {
            kind: "literal",
            value: "code",
          },
          {
            kind: "literal",
            value: "em",
          },
          {
            kind: "literal",
            value: "strong",
          },
          {
            kind: "literal",
            value: "small",
          },
          {
            kind: "literal",
            value: "abbr",
          },
          {
            kind: "literal",
            value: "time",
          },
        ],
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
  },
  Toast: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    variant: {
      type: "KumoToastVariant",
      values: ["default", "success", "error", "warning", "info"],
      runtime: {
        kind: "string",
      },
    },
  },
  Tooltip: {
    children: {
      type: "Snippet",
      runtime: {
        kind: "snippet",
      },
    },
    to: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    delayDuration: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    skipDelayDuration: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    disableHoverableContent: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    disabled: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    content: {
      type: "Snippet | string",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "snippet",
          },
          {
            kind: "string",
          },
        ],
      },
    },
    render: {
      type: "Snippet<[{ props: Record<string, unknown> }]>",
      runtime: {
        kind: "snippet",
      },
    },
    side: {
      type: "KumoTooltipSide",
      values: ["top", "bottom", "left", "right"],
      runtime: {
        kind: "string",
      },
    },
    align: {
      type: "KumoTooltipAlign",
      runtime: {
        kind: "union",
        options: [
          {
            kind: "literal",
            value: "start",
          },
          {
            kind: "literal",
            value: "center",
          },
          {
            kind: "literal",
            value: "end",
          },
        ],
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    container: {
      type: 'PortalProps["to"]',
      runtime: {
        kind: "union",
        options: [
          {
            kind: "string",
          },
          {
            kind: "object",
          },
        ],
      },
    },
    delay: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    closeDelay: {
      type: "number",
      runtime: {
        kind: "number",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
  },
  DeleteResource: {
    caseSensitive: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    class: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    deleteButtonText: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    errorMessage: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    isDeleting: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    onDelete: {
      type: "() => void | Promise<void>",
      runtime: {
        kind: "function",
      },
    },
    onOpenChange: {
      type: "(open: boolean) => void",
      runtime: {
        kind: "function",
      },
    },
    open: {
      type: "boolean",
      runtime: {
        kind: "boolean",
      },
    },
    resourceName: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    resourceType: {
      type: "string",
      runtime: {
        kind: "string",
      },
    },
    size: {
      type: "KumoDeleteResourceSize",
      values: ["sm", "base"],
      runtime: {
        kind: "string",
      },
    },
  },
} as const;
