// Generated by scripts/generate-basic-registry.mjs.
export const KUMO_COMPONENT_PROP_SCHEMAS = {
  Autocomplete: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    container: {
      type: 'PortalProps["to"]',
    },
    sideOffset: {
      type: "number",
    },
    "aria-label": {
      type: "string",
    },
    autocomplete: {
      type: 'HTMLInputAttributes["autocomplete"]',
    },
    clearOnDeselect: {
      type: "boolean",
    },
    defaultValue: {
      type: "string",
    },
    disabled: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    onblur: {
      type: "(event: FocusEvent & { currentTarget: HTMLInputElement }) => void",
    },
    onfocus: {
      type: "(event: FocusEvent & { currentTarget: HTMLInputElement }) => void",
    },
    oninput: {
      type: "(event: Event & { currentTarget: HTMLInputElement }) => void",
    },
    onkeydown: {
      type: "(event: KeyboardEvent & { currentTarget: HTMLInputElement }) => void",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    placeholder: {
      type: "string",
    },
    required: {
      type: "boolean",
    },
    size: {
      type: "KumoAutocompleteSize",
    },
    label: {
      type: "Snippet | string",
    },
    value: {
      type: "string",
    },
    allowDeselect: {
      type: "boolean",
    },
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
    },
    items: {
      type: "AutocompleteItemDescriptor[]",
    },
    labelTooltip: {
      type: "Snippet",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    open: {
      type: "boolean",
    },
  },
  Badge: {
    variant: {
      type: "KumoBadgeVariant",
      values: [
        "primary",
        "secondary",
        "error",
        "warning",
        "success",
        "destructive",
        "info",
        "beta",
        "outline",
        "red",
        "green",
        "neutral",
        "orange",
        "purple",
        "teal",
        "teal-subtle",
        "blue",
      ],
    },
    class: {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
  },
  Banner: {
    action: {
      type: "Snippet",
    },
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    description: {
      type: "Snippet | string",
    },
    icon: {
      type: "Snippet",
    },
    text: {
      type: "string",
    },
    title: {
      type: "string",
    },
    variant: {
      type: "KumoBannerVariant",
      values: ["default", "alert", "error"],
    },
  },
  Breadcrumbs: {
    class: {
      type: "string",
    },
    copiedLabel: {
      type: "string",
    },
    label: {
      type: "string",
    },
    onCopy: {
      type: "() => void",
    },
    text: {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
    icon: {
      type: "Snippet",
    },
    loading: {
      type: "boolean",
    },
    mobileChildren: {
      type: "Snippet",
    },
    size: {
      type: "KumoBreadcrumbsSize",
      values: ["sm", "base"],
    },
  },
  Button: {
    shape: {
      type: "KumoButtonShape",
      values: ["base", "square", "circle"],
    },
    size: {
      type: "KumoButtonSize",
      values: ["xs", "sm", "base", "lg"],
    },
    variant: {
      type: "KumoButtonVariant",
      values: ["primary", "secondary", "ghost", "destructive", "secondary-destructive", "outline"],
    },
    class: {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
    icon: {
      type: "Snippet",
    },
    loading: {
      type: "boolean",
    },
    title: {
      type: "string",
    },
    external: {
      type: "boolean",
    },
    linksExternal: {
      type: "boolean",
    },
  },
  Checkbox: {
    legend: {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
    error: {
      type: "string",
    },
    description: {
      type: "Snippet | string",
    },
    defaultValue: {
      type: "string[]",
    },
    value: {
      type: "string",
    },
    onValueChange: {
      type: "(value: string[]) => void",
    },
    allValues: {
      type: "string[]",
    },
    disabled: {
      type: "boolean",
    },
    controlFirst: {
      type: "boolean",
    },
    class: {
      type: "string",
    },
    name: {
      type: "string",
    },
    required: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    variant: {
      type: "KumoCheckboxVariant",
      values: ["default", "error"],
    },
    label: {
      type: "Snippet | string",
    },
    checked: {
      type: "boolean",
    },
    indeterminate: {
      type: "boolean",
    },
    onCheckedChange: {
      type: "(checked: boolean) => void",
    },
    "aria-label": {
      type: "string",
    },
    "aria-labelledby": {
      type: "string",
    },
    labelTooltip: {
      type: "Snippet",
    },
  },
  ClipboardText: {
    class: {
      type: "string",
    },
    labels: {
      type: "ClipboardTextLabels",
    },
    onCopy: {
      type: "() => void",
    },
    size: {
      type: "KumoClipboardTextSize",
      values: ["sm", "base", "lg"],
    },
    text: {
      type: "string",
    },
    textToCopy: {
      type: "string",
    },
    tooltip: {
      type: "ClipboardTextTooltipConfig",
    },
  },
  CloudflareLogo: {
    class: {
      type: "string",
    },
    color: {
      type: "CloudflareLogoColor",
      values: ["color", "black", "white"],
    },
    variant: {
      type: "CloudflareLogoVariant",
      values: ["glyph", "full"],
    },
  },
  Collapsible: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    forceMount: {
      type: "boolean",
    },
    hiddenUntilFound: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    disabled: {
      type: "boolean",
    },
    open: {
      type: "boolean",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
    },
  },
  Combobox: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    container: {
      type: 'PortalProps["to"]',
    },
    sideOffset: {
      type: "number",
    },
    "aria-label": {
      type: "string",
    },
    autocomplete: {
      type: 'HTMLInputAttributes["autocomplete"]',
    },
    clearOnDeselect: {
      type: "boolean",
    },
    defaultValue: {
      type: "string | string[]",
    },
    disabled: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    oninput: {
      type: "(event: Event & { currentTarget: HTMLInputElement }) => void",
    },
    onValueChange: {
      type: "(value: string | string[]) => void",
    },
    placeholder: {
      type: "string",
    },
    required: {
      type: "boolean",
    },
    size: {
      type: "KumoComboboxSize",
    },
    label: {
      type: "Snippet | string",
    },
    value: {
      type: "string | string[]",
    },
    clearLabel: {
      type: "string",
    },
    showOptionsLabel: {
      type: "string",
    },
    allowDeselect: {
      type: "boolean",
    },
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
    },
    items: {
      type: "ComboboxItemDescriptor[]",
    },
    labelTooltip: {
      type: "Snippet",
    },
    multiple: {
      type: "boolean",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    open: {
      type: "boolean",
    },
    inputSide: {
      type: "KumoComboboxInputSide",
      values: ["right", "top"],
    },
  },
  CommandPalette: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    open: {
      type: "boolean",
    },
    forceMount: {
      type: "boolean",
    },
    value: {
      type: "string",
    },
    "aria-label": {
      type: "string",
    },
    autocomplete: {
      type: 'HTMLInputAttributes["autocomplete"]',
    },
    autofocus: {
      type: "boolean",
    },
    leading: {
      type: "Snippet",
    },
    onkeydown: {
      type: "(event: KeyboardEvent & { currentTarget: HTMLInputElement }) => void",
    },
    placeholder: {
      type: "string",
    },
    trailing: {
      type: "Snippet",
    },
    disabled: {
      type: "boolean",
    },
    keywords: {
      type: "string[]",
    },
    onSelect: {
      type: "() => void",
    },
    progress: {
      type: "number",
    },
    breadcrumbHighlights: {
      type: "HighlightRange[][]",
    },
    breadcrumbs: {
      type: "string[]",
    },
    description: {
      type: "string",
    },
    external: {
      type: "boolean",
    },
    icon: {
      type: "Snippet",
    },
    nonInteractive: {
      type: "boolean",
    },
    showArrow: {
      type: "boolean",
    },
    title: {
      type: "string",
    },
    titleHighlights: {
      type: "HighlightRange[]",
    },
    filter: {
      type: "(value: string, search: string, keywords?: string[]) => number",
    },
    label: {
      type: "string",
    },
    loop: {
      type: "boolean",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    shouldFilter: {
      type: "boolean",
    },
    highlights: {
      type: "HighlightRange[]",
    },
    text: {
      type: "string",
    },
  },
  Code: {
    code: {
      type: "string",
    },
    lang: {
      type: "KumoCodeLang",
      values: ["ts", "tsx", "jsonc", "bash", "css"],
    },
    class: {
      type: "string",
    },
    values: {
      type: "Record<string, { highlight?: boolean; value: string }>",
    },
  },
  Chart: {
    class: {
      type: "string",
    },
    color: {
      type: "string",
    },
    inactive: {
      type: "boolean",
    },
    name: {
      type: "string",
    },
    unit: {
      type: "string",
    },
    value: {
      type: "string",
    },
    className: {
      type: "string",
    },
    defaultNodeColor: {
      type: "string",
    },
    echarts: {
      type: "typeof echarts",
    },
    formatValue: {
      type: "(value: number) => string",
    },
    height: {
      type: "number",
    },
    isDarkMode: {
      type: "boolean",
    },
    left: {
      type: "number | string",
    },
    linkColor: {
      type: '"gradient" | "gray"',
      values: ["gradient", "gray"],
    },
    linkOpacity: {
      type: "number",
    },
    links: {
      type: "SankeyLinkData[]",
    },
    nodePadding: {
      type: "number",
    },
    nodeWidth: {
      type: "number",
    },
    nodes: {
      type: "SankeyNodeData[]",
    },
    onLinkClick: {
      type: "(link: SankeyLinkData) => void",
    },
    onNodeClick: {
      type: "(node: SankeyNodeData) => void",
    },
    right: {
      type: "number | string",
    },
    showNodeValues: {
      type: "boolean",
    },
    showTooltip: {
      type: "boolean",
    },
    tooltipFormatter: {
      type: "(params: SankeyTooltipParams) => string",
    },
    ariaDescription: {
      type: "string",
    },
    data: {
      type: "TimeseriesData[]",
    },
    gradient: {
      type: "boolean",
    },
    incomplete: {
      type: "{ after?: number; before?: number }",
    },
    loading: {
      type: "boolean",
    },
    onTimeRangeChange: {
      type: "(from: number, to: number) => void",
    },
    optionUpdateBehavior: {
      type: "SetOptionOpts",
    },
    tooltipValueFormat: {
      type: "(value: number) => string",
    },
    type: {
      type: '"bar" | "line"',
      values: ["bar", "line"],
    },
    xAxisName: {
      type: "string",
    },
    xAxisTickCount: {
      type: "number",
    },
    xAxisTickFormat: {
      type: "(value: number) => string",
    },
    yAxisName: {
      type: "string",
    },
    yAxisTickCount: {
      type: "number",
    },
    yAxisTickFormat: {
      type: "(value: number) => string",
    },
    yAxisTickLabelFormat: {
      type: "(value: number) => string",
    },
    onEvents: {
      type: "Partial<ChartEvents>",
    },
    options: {
      type: "KumoChartOption",
    },
    ref: {
      type: "echarts.ECharts | null",
    },
  },
  DatePicker: {
    mode: {
      type: "DatePickerMode",
    },
    months: {
      type: "Month<DateValue>[]",
    },
    weekdays: {
      type: "string[]",
    },
    calendarLabel: {
      type: "string",
    },
    children: {
      type: "Snippet<[DatePickerSnippetProps]>",
    },
    class: {
      type: "string",
    },
    disableDaysOutsideMonth: {
      type: "boolean",
    },
    disabled: {
      type: "boolean",
    },
    excludeDisabled: {
      type: "boolean",
    },
    fixedWeeks: {
      type: "boolean",
    },
    initialFocus: {
      type: "boolean",
    },
    isDateDisabled: {
      type: "DateMatcher",
    },
    isDateUnavailable: {
      type: "DateMatcher",
    },
    locale: {
      type: "string",
    },
    maxDays: {
      type: "number",
    },
    maxValue: {
      type: "DateValue",
    },
    minDays: {
      type: "number",
    },
    minValue: {
      type: "DateValue",
    },
    monthFormat: {
      type: 'Intl.DateTimeFormatOptions["month"] | ((month: number) => string)',
    },
    numberOfMonths: {
      type: "number",
    },
    onChange: {
      type: "(value: DatePickerValue) => void",
    },
    onEndValueChange: {
      type: "(value: DateValue | undefined) => void",
    },
    onPlaceholderChange: {
      type: "(value: DateValue) => void",
    },
    onStartValueChange: {
      type: "(value: DateValue | undefined) => void",
    },
    onValueChange: {
      type: "(value: DatePickerValue) => void",
    },
    pagedNavigation: {
      type: "boolean",
    },
    placeholder: {
      type: "DateValue",
    },
    preventDeselect: {
      type: "boolean",
    },
    readonly: {
      type: "boolean",
    },
    ref: {
      type: "HTMLDivElement | null",
    },
    value: {
      type: "DatePickerValue",
    },
    weekStartsOn: {
      type: "WeekStartsOn",
    },
    weekdayFormat: {
      type: 'Intl.DateTimeFormatOptions["weekday"]',
    },
    yearFormat: {
      type: 'Intl.DateTimeFormatOptions["year"] | ((year: number) => string)',
    },
  },
  DateRangePicker: {
    class: {
      type: "string",
    },
    className: {
      type: "string",
    },
    onEndDateChange: {
      type: "(date: Date | null) => void",
    },
    onStartDateChange: {
      type: "(date: Date | null) => void",
    },
    onValueChange: {
      type: "(value: DateRange) => void",
    },
    size: {
      type: "KumoDateRangePickerSize",
      values: ["sm", "base", "lg"],
    },
    timezone: {
      type: "string",
    },
    value: {
      type: "DateRange",
    },
    variant: {
      type: "KumoDateRangePickerVariant",
      values: ["default", "subtle"],
    },
  },
  Dialog: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    disabled: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    container: {
      type: 'PortalProps["to"]',
    },
    size: {
      type: "KumoDialogSize",
      values: ["base", "sm", "lg", "xl"],
    },
    style: {
      type: "string",
    },
    role: {
      type: "KumoDialogRole",
      values: ["dialog", "alertdialog"],
    },
    open: {
      type: "boolean",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    level: {
      type: "1 | 2 | 3 | 4 | 5 | 6",
    },
  },
  Dropdown: {
    children: {
      type: "Snippet",
    },
    dir: {
      type: '"ltr" | "rtl"',
      values: ["ltr", "rtl"],
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
    },
    open: {
      type: "boolean",
    },
    variant: {
      type: "KumoDropdownVariant",
      values: ["default", "danger"],
    },
  },
  Empty: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    commandLine: {
      type: "string",
    },
    contents: {
      type: "Snippet",
    },
    description: {
      type: "string",
    },
    icon: {
      type: "Snippet",
    },
    size: {
      type: "KumoEmptySize",
      values: ["sm", "base", "lg"],
    },
    title: {
      type: "string",
    },
  },
  Field: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "NormalizedFieldError",
    },
    for: {
      type: "string",
    },
    hideLabel: {
      type: "boolean",
    },
    label: {
      type: "Snippet | string",
    },
    labelTooltip: {
      type: "Snippet",
    },
    required: {
      type: "boolean",
    },
    controlFirst: {
      type: "boolean",
    },
  },
  Flow: {
    children: {
      type: "Snippet",
    },
    connectors: {
      type: "FlowConnector[]",
    },
    markerId: {
      type: "string",
    },
    render: {
      type: "FlowNodeRenderSnippet",
    },
    type: {
      type: "FlowAnchorType",
    },
    class: {
      type: "string",
    },
    id: {
      type: "string",
    },
    disabled: {
      type: "boolean",
    },
    align: {
      type: "FlowAlign",
    },
    canvas: {
      type: "boolean",
    },
    onOverflowChange: {
      type: "(overflow: { x: boolean; y: boolean }) => void",
    },
    orientation: {
      type: "FlowOrientation",
    },
    padding: {
      type: "{ x?: number; y?: number }",
    },
    action: {
      type: "Action<HTMLElement>",
    },
    attrs: {
      type: '{ "data-node-id": string; "data-node-index": number; "data-testid": string; style: string; }',
    },
    index: {
      type: "number",
    },
  },
  Grid: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    gap: {
      type: "KumoGridGap",
      values: ["none", "sm", "base", "lg"],
    },
    mobileDivider: {
      type: "boolean",
    },
    variant: {
      type: "KumoGridVariant",
      values: ["2up", "side-by-side", "2-1", "1-2", "1-3up", "3up", "4up", "6up", "1-2-4up"],
    },
  },
  Input: {
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
    },
    label: {
      type: "Snippet | string",
    },
    labelTooltip: {
      type: "Snippet",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    size: {
      type: "KumoInputSize",
      values: ["xs", "sm", "base", "lg"],
    },
    value: {
      type: "string | number | string[] | undefined",
    },
    variant: {
      type: "KumoInputVariant",
      values: ["default", "error"],
    },
    passwordManagerIgnore: {
      type: "boolean",
    },
    focusIndicator: {
      type: "boolean",
    },
    parentFocusIndicator: {
      type: "boolean",
    },
  },
  InputGroup: {
    align: {
      type: '"start" | "end"',
      values: ["start", "end"],
    },
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    containsButton: {
      type: "boolean",
    },
    tooltip: {
      type: "Snippet | string",
    },
    tooltipSide: {
      type: "KumoTooltipSide",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    value: {
      type: "string | number | string[] | undefined",
    },
    description: {
      type: "Snippet | string",
    },
    disabled: {
      type: "boolean",
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
    },
    focusMode: {
      type: "InputGroupFocusMode",
    },
    label: {
      type: "Snippet | string",
    },
    labelTooltip: {
      type: "Snippet",
    },
    required: {
      type: "boolean",
    },
    size: {
      type: "KumoInputSize",
      values: ["xs", "sm", "base", "lg"],
    },
  },
  Label: {
    children: {
      type: "Snippet",
    },
    showOptional: {
      type: "boolean",
    },
    tooltip: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    for: {
      type: "string",
    },
    id: {
      type: "string",
    },
    asContent: {
      type: "boolean",
    },
  },
  LayerCard: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    as: {
      type: "keyof HTMLElementTagNameMap",
    },
    layered: {
      type: "boolean",
    },
  },
  Switch: {
    checked: {
      type: "boolean",
    },
    class: {
      type: "string",
    },
    disabled: {
      type: "boolean",
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    onCheckedChange: {
      type: "(checked: boolean) => void",
    },
    required: {
      type: "boolean",
    },
    size: {
      type: "KumoSwitchSize",
      values: ["sm", "base", "lg"],
    },
    transitioning: {
      type: "boolean",
    },
    value: {
      type: "string",
    },
    variant: {
      type: "KumoSwitchVariant",
      values: ["default", "neutral"],
    },
    "aria-label": {
      type: "string",
    },
    "aria-labelledby": {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
    controlFirst: {
      type: "boolean",
    },
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "string",
    },
    legend: {
      type: "string",
    },
    label: {
      type: "Snippet | string",
    },
    labelTooltip: {
      type: "Snippet",
    },
  },
  TableOfContents: {
    active: {
      type: "boolean",
    },
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    href: {
      type: "string",
    },
    label: {
      type: "string",
    },
    child: {
      type: "Snippet<[{ props: ItemProps & { class: string } }]>",
    },
  },
  Tabs: {
    activateOnFocus: {
      type: "boolean",
    },
    class: {
      type: "string",
    },
    indicatorClassName: {
      type: "string",
    },
    listClassName: {
      type: "string",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    selectedValue: {
      type: "string",
    },
    size: {
      type: "KumoTabsSize",
      values: ["base", "sm"],
    },
    tabs: {
      type: "TabsItem[]",
    },
    value: {
      type: "string",
    },
    variant: {
      type: "KumoTabsVariant",
      values: ["segmented", "underline"],
    },
  },
  Link: {
    class: {
      type: "string",
    },
    variant: {
      type: "KumoLinkVariant",
      values: ["inline", "current", "plain"],
    },
    children: {
      type: "Snippet",
    },
    to: {
      type: "string",
    },
  },
  Loader: {
    "aria-label": {
      type: "string",
    },
    size: {
      type: "KumoLoaderSize | number",
      values: ["sm", "base", "lg"],
    },
    blockHeight: {
      type: "string | number",
    },
    class: {
      type: "string",
    },
    maxDelay: {
      type: "number",
    },
    maxDuration: {
      type: "number",
    },
    maxWidth: {
      type: "number",
    },
    minDelay: {
      type: "number",
    },
    minDuration: {
      type: "number",
    },
    minWidth: {
      type: "number",
    },
  },
  Menubar: {
    class: {
      type: "string",
    },
    isActive: {
      type: "number | boolean | string | undefined",
    },
    optionIds: {
      type: "boolean",
    },
    options: {
      type: "MenuBarOption[]",
    },
  },
  Meter: {
    value: {
      type: "number",
    },
    min: {
      type: "number",
    },
    max: {
      type: "number",
    },
    customValue: {
      type: "string",
    },
    label: {
      type: "string",
    },
    showValue: {
      type: "boolean",
    },
    class: {
      type: "string",
    },
    trackClass: {
      type: "string",
    },
    indicatorClass: {
      type: "string",
    },
    id: {
      type: "string",
    },
  },
  Pagination: {
    class: {
      type: "string",
    },
    controls: {
      type: "KumoPaginationControls",
      values: ["full", "simple"],
    },
    pageSelector: {
      type: '"input" | "dropdown"',
      values: ["input", "dropdown"],
    },
    text: {
      type: "Snippet<[props: PaginationInfoSnippetProps]>",
    },
    label: {
      type: "Snippet | string",
    },
    onChange: {
      type: "(size: number) => void",
    },
    options: {
      type: "number[]",
    },
    value: {
      type: "number",
    },
    page: {
      type: "number",
    },
    pageShowingRange: {
      type: "string",
    },
    perPage: {
      type: "number",
    },
    totalCount: {
      type: "number",
    },
    children: {
      type: "Snippet",
    },
    labels: {
      type: "PaginationLabels",
    },
    setPage: {
      type: "(page: number) => void",
    },
  },
  Popover: {
    children: {
      type: "Snippet",
    },
    open: {
      type: "boolean",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    onOpenChangeComplete: {
      type: "(open: boolean) => void",
    },
    side: {
      type: "KumoPopoverSide",
      values: ["top", "bottom", "left", "right"],
    },
  },
  Radio: {
    appearance: {
      type: "KumoRadioAppearance",
      values: ["default", "card"],
    },
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    controlPosition: {
      type: "RadioControlPosition",
    },
    defaultValue: {
      type: "string",
    },
    description: {
      type: "Snippet | string",
    },
    disabled: {
      type: "boolean",
    },
    error: {
      type: "string",
    },
    legend: {
      type: "string",
    },
    name: {
      type: "string",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    orientation: {
      type: '"vertical" | "horizontal"',
      values: ["vertical", "horizontal"],
    },
    required: {
      type: "boolean",
    },
    value: {
      type: "string",
    },
    id: {
      type: "string",
    },
    label: {
      type: "Snippet | string",
    },
    variant: {
      type: "KumoRadioVariant",
      values: ["default", "error"],
    },
  },
  Select: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    disabled: {
      type: "boolean",
    },
    label: {
      type: "Snippet | string",
    },
    value: {
      type: "string | string[]",
    },
    "aria-label": {
      type: "string",
    },
    "aria-labelledby": {
      type: "string",
    },
    allowDeselect: {
      type: "boolean",
    },
    container: {
      type: 'PortalProps["to"]',
    },
    defaultValue: {
      type: "string | string[]",
    },
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
    },
    hideLabel: {
      type: "boolean",
    },
    items: {
      type: "SelectItems",
    },
    labelTooltip: {
      type: "Snippet",
    },
    loading: {
      type: "boolean",
    },
    multiple: {
      type: "boolean",
    },
    name: {
      type: "string",
    },
    onValueChange: {
      type: "(value: string | string[]) => void",
    },
    placeholder: {
      type: "string",
    },
    required: {
      type: "boolean",
    },
    size: {
      type: "KumoSelectSize",
    },
  },
  SensitiveInput: {
    class: {
      type: "string",
    },
    defaultValue: {
      type: "string",
    },
    description: {
      type: "Snippet | string",
    },
    error: {
      type: "string | { message: Snippet | string; match: FieldErrorMatch }",
    },
    label: {
      type: "Snippet | string",
    },
    labelTooltip: {
      type: "Snippet",
    },
    onCopy: {
      type: "() => void",
    },
    onValueChange: {
      type: "(value: string) => void",
    },
    readOnly: {
      type: "boolean",
    },
    readonly: {
      type: "boolean | null",
    },
    size: {
      type: "KumoSensitiveInputSize",
    },
    value: {
      type: "string",
    },
    variant: {
      type: "KumoSensitiveInputVariant",
    },
  },
  Sidebar: {
    class: {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
    collapsible: {
      type: "SidebarCollapsible",
      values: ["icon", "offcanvas", "none"],
    },
    defaultOpen: {
      type: "boolean",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    open: {
      type: "boolean",
    },
    placeholder: {
      type: "string",
    },
    shortcut: {
      type: "string",
    },
    active: {
      type: "boolean",
    },
    href: {
      type: "string",
    },
    icon: {
      type: "Snippet",
    },
    linkProps: {
      type: 'Omit<HTMLAnchorAttributes, "children" | "class" | "href">',
    },
    size: {
      type: "SidebarMenuButtonSize",
    },
    tooltip: {
      type: "string",
    },
    defaultWidth: {
      type: "number",
    },
    maxWidth: {
      type: "number",
    },
    minWidth: {
      type: "number",
    },
    onWidthChange: {
      type: "(width: number) => void",
    },
    resizable: {
      type: "boolean",
    },
    side: {
      type: "SidebarSide",
      values: ["left", "right"],
    },
    style: {
      type: "string",
    },
    variant: {
      type: "SidebarVariant",
      values: ["sidebar", "floating", "inset"],
    },
    width: {
      type: "number",
    },
    section: {
      type: '"content" | "footer" | "header"',
      values: ["content", "footer", "header"],
    },
    ref: {
      type: "HTMLElement | null",
    },
  },
  Surface: {
    as: {
      type: "keyof HTMLElementTagNameMap",
    },
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    color: {
      type: "KumoSurfaceColor",
      values: ["primary", "secondary"],
    },
  },
  Table: {
    children: {
      type: "Snippet",
    },
    class: {
      type: "string",
    },
    sticky: {
      type: "boolean",
      values: ["left", "right"],
    },
    checked: {
      type: "boolean",
    },
    disabled: {
      type: "boolean",
    },
    indeterminate: {
      type: "boolean",
    },
    label: {
      type: "string",
    },
    onCheckedChange: {
      type: "(checked: boolean, eventDetails?: CheckboxChangeEventDetails) => void",
    },
    onValueChange: {
      type: "(checked: boolean) => void",
    },
    variant: {
      type: "KumoTableRowVariant",
      values: ["default", "selected"],
    },
    layout: {
      type: "KumoTableLayout",
      values: ["auto", "fixed"],
    },
  },
  Text: {
    variant: {
      type: "KumoTextVariant",
      values: [
        "heading1",
        "heading2",
        "heading3",
        "body",
        "secondary",
        "success",
        "error",
        "mono",
        "mono-secondary",
      ],
    },
    size: {
      type: "KumoTextSize",
      values: ["xs", "sm", "base", "lg"],
    },
    bold: {
      type: "boolean",
    },
    truncate: {
      type: "boolean",
    },
    as: {
      type: "TextElement",
    },
    DANGEROUS_className: {
      type: "string",
    },
    DANGEROUS_style: {
      type: "string",
    },
    children: {
      type: "Snippet",
    },
  },
  Toast: {
    children: {
      type: "Snippet",
    },
    variant: {
      type: "KumoToastVariant",
      values: ["default", "success", "error", "warning", "info"],
    },
  },
  Tooltip: {
    children: {
      type: "Snippet",
    },
    delayDuration: {
      type: "number",
    },
    skipDelayDuration: {
      type: "number",
    },
    disableHoverableContent: {
      type: "boolean",
    },
    disabled: {
      type: "boolean",
    },
    content: {
      type: "Snippet | string",
    },
    side: {
      type: "KumoTooltipSide",
      values: ["top", "bottom", "left", "right"],
    },
    align: {
      type: "KumoTooltipAlign",
    },
    class: {
      type: "string",
    },
    container: {
      type: 'PortalProps["to"]',
    },
    delay: {
      type: "number",
    },
    closeDelay: {
      type: "number",
    },
  },
  DeleteResource: {
    caseSensitive: {
      type: "boolean",
    },
    class: {
      type: "string",
    },
    className: {
      type: "string",
    },
    deleteButtonText: {
      type: "string",
    },
    errorMessage: {
      type: "string",
    },
    isDeleting: {
      type: "boolean",
    },
    onDelete: {
      type: "() => void | Promise<void>",
    },
    onOpenChange: {
      type: "(open: boolean) => void",
    },
    open: {
      type: "boolean",
    },
    resourceName: {
      type: "string",
    },
    resourceType: {
      type: "string",
    },
    size: {
      type: "KumoDeleteResourceSize",
      values: ["sm", "base"],
    },
  },
} as const;
