// Generated by scripts/generate-basic-registry.mjs.
export const KUMO_COMPONENT_PROP_SCHEMAS = {
  Autocomplete: {},
  Badge: {
    variant: {
      type: "KumoBadgeVariant",
      values: [
        "primary",
        "secondary",
        "error",
        "warning",
        "success",
        "destructive",
        "info",
        "beta",
        "outline",
        "red",
        "green",
        "neutral",
        "orange",
        "purple",
        "teal",
        "teal-subtle",
        "blue",
      ],
    },
  },
  Banner: {
    variant: {
      type: "KumoBannerVariant",
      values: ["default", "alert", "error"],
    },
  },
  Breadcrumbs: {
    size: {
      type: "KumoBreadcrumbsSize",
      values: ["sm", "base"],
    },
  },
  Button: {
    shape: {
      type: "KumoButtonShape",
      values: ["base", "square", "circle"],
    },
    size: {
      type: "KumoButtonSize",
      values: ["xs", "sm", "base", "lg"],
    },
    variant: {
      type: "KumoButtonVariant",
      values: ["primary", "secondary", "ghost", "destructive", "secondary-destructive", "outline"],
    },
  },
  Checkbox: {
    variant: {
      type: "KumoCheckboxVariant",
      values: ["default", "error"],
    },
  },
  ClipboardText: {
    size: {
      type: "KumoClipboardTextSize",
      values: ["sm", "base", "lg"],
    },
  },
  CloudflareLogo: {
    color: {
      type: "CloudflareLogoColor",
      values: ["color", "black", "white"],
    },
    variant: {
      type: "CloudflareLogoVariant",
      values: ["glyph", "full"],
    },
  },
  Collapsible: {},
  Combobox: {
    inputSide: {
      type: "KumoComboboxInputSide",
      values: ["right", "top"],
    },
  },
  CommandPalette: {},
  Code: {
    lang: {
      type: "KumoCodeLang",
      values: ["ts", "tsx", "jsonc", "bash", "css"],
    },
  },
  Chart: {},
  DatePicker: {},
  DateRangePicker: {
    size: {
      type: "KumoDateRangePickerSize",
      values: ["sm", "base", "lg"],
    },
    variant: {
      type: "KumoDateRangePickerVariant",
      values: ["default", "subtle"],
    },
  },
  Dialog: {
    size: {
      type: "KumoDialogSize",
      values: ["base", "sm", "lg", "xl"],
    },
    role: {
      type: "KumoDialogRole",
      values: ["dialog", "alertdialog"],
    },
  },
  Dropdown: {
    variant: {
      type: "KumoDropdownVariant",
      values: ["default", "danger"],
    },
  },
  Empty: {
    size: {
      type: "KumoEmptySize",
      values: ["sm", "base", "lg"],
    },
  },
  Field: {},
  Flow: {},
  Grid: {
    gap: {
      type: "KumoGridGap",
      values: ["none", "sm", "base", "lg"],
    },
    variant: {
      type: "KumoGridVariant",
      values: ["2up", "side-by-side", "2-1", "1-2", "1-3up", "3up", "4up", "6up", "1-2-4up"],
    },
  },
  Input: {
    size: {
      type: "KumoInputSize",
      values: ["xs", "sm", "base", "lg"],
    },
    variant: {
      type: "KumoInputVariant",
      values: ["default", "error"],
    },
  },
  InputGroup: {
    size: {
      type: "KumoInputSize",
      values: ["xs", "sm", "base", "lg"],
    },
  },
  Label: {},
  LayerCard: {},
  Switch: {
    size: {
      type: "KumoSwitchSize",
      values: ["sm", "base", "lg"],
    },
    variant: {
      type: "KumoSwitchVariant",
      values: ["default", "neutral"],
    },
  },
  TableOfContents: {},
  Tabs: {
    size: {
      type: "KumoTabsSize",
      values: ["base", "sm"],
    },
    variant: {
      type: "KumoTabsVariant",
      values: ["segmented", "underline"],
    },
  },
  Link: {
    variant: {
      type: "KumoLinkVariant",
      values: ["inline", "current", "plain"],
    },
  },
  Loader: {
    size: {
      type: "KumoLoaderSize | number",
      values: ["sm", "base", "lg"],
    },
  },
  Menubar: {},
  Meter: {},
  Pagination: {
    controls: {
      type: "KumoPaginationControls",
      values: ["full", "simple"],
    },
  },
  Popover: {
    side: {
      type: "KumoPopoverSide",
      values: ["top", "bottom", "left", "right"],
    },
  },
  Radio: {
    appearance: {
      type: "KumoRadioAppearance",
      values: ["default", "card"],
    },
    variant: {
      type: "KumoRadioVariant",
      values: ["default", "error"],
    },
  },
  Select: {},
  SensitiveInput: {},
  Sidebar: {
    collapsible: {
      type: "SidebarCollapsible",
      values: ["icon", "offcanvas", "none"],
    },
    side: {
      type: "SidebarSide",
      values: ["left", "right"],
    },
    variant: {
      type: "SidebarVariant",
      values: ["sidebar", "floating", "inset"],
    },
  },
  Surface: {
    color: {
      type: "KumoSurfaceColor",
      values: ["primary", "secondary"],
    },
  },
  Table: {
    sticky: {
      type: "boolean",
      values: ["left", "right"],
    },
    variant: {
      type: "KumoTableRowVariant",
      values: ["default", "selected"],
    },
    layout: {
      type: "KumoTableLayout",
      values: ["auto", "fixed"],
    },
  },
  Text: {
    variant: {
      type: "KumoTextVariant",
      values: [
        "heading1",
        "heading2",
        "heading3",
        "body",
        "secondary",
        "success",
        "error",
        "mono",
        "mono-secondary",
      ],
    },
    size: {
      type: "KumoTextSize",
      values: ["xs", "sm", "base", "lg"],
    },
  },
  Toast: {
    variant: {
      type: "KumoToastVariant",
      values: ["default", "success", "error", "warning", "info"],
    },
  },
  Tooltip: {
    side: {
      type: "KumoTooltipSide",
      values: ["top", "bottom", "left", "right"],
    },
  },
  DeleteResource: {
    size: {
      type: "KumoDeleteResourceSize",
      values: ["sm", "base"],
    },
  },
} as const;
